name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the ephemeris API Docker image
      run: docker build ./api --file api/Dockerfile --tag astrology-api:$(date +%s)
    - name: Build the Telegram bot Docker image
      run: docker build ./bot --file bot/Dockerfile --tag astrology-bot:$(date +%s)
